const terms = `
# Terms of Use
Welcome to [www.coronavirusonlinetherapy.com](www.coronavirusonlinetherapy.com); and [www.covid19onlinetherapy.com](www.covid19onlinetherapy.com) (collectively the "Website"). The Website is operated by Jennifer Silacci, LCSW (“Us” or “We”).  The Website is made available for use only by individuals seeking free referrals for psychotherapeutic counseling during the coronavirus pandemic (“Client(s)” or “You”) with private practice psychotherapists (“Therapists”) conditioned on each person’s acceptance without modification of this Agreement. Us or We, Client(s) or You or Therapists are sometimes singularly referred to as “Party” and collectively as “Parties.” Please carefully read these terms of use (this "Agreement") because this legal Agreement contains the terms and conditions which governs the Client’s and Therapist’s access to and use of the Website and the free referral services provided at any time by Us (collectively the “Services”). By accessing the Website and clicking “agree” or “accept” or other similarly worded button or entry field, Clients and Therapists agree to be legally bound by this Agreement. This Agreement applies to all transactions, relationships, and interactions between Client and Us and the Therapists and Us. The use or access of the Website or any of the Services or the taking of other actions which indicates acceptance of this Agreement constitutes Client’s and Therapist’s acceptance and agreement, without modification, of all of the terms and conditions in this Agreement. If any of the aforementioned Parties do not accept and agree with this Agreement, it may not use the referral Services or access the Website.  

# This Website and the Services do not provide Psychotherapy or Mental Health Services
We do not offer or provide any direct psychotherapy services of any kind or nature. The Website is for informational purposes only and it is intended to solely connect Clients with Therapists. Therapists include, but are not limited to Licensed Social Workers, Psychologists, Marriage and Family Therapists, Licensed Mental Health Counselors, and Licensed Art Therapists. We do not recommend or endorse any specific Therapists even if referred through this Website nor any tests, procedures, therapies, opinions or other information whatsoever. Nothing in the content of the Website or the Services is intended to be a substitute for professional psychotherapeutic diagnosis, advice, or treatment. Always seek the advice of your mental health practitioner or other qualified provider with any questions you may have with respect to a mental health condition.

# No Licensure or background checks of Therapists
We do not conduct or perform any due diligence, verification or inquiry checks on the Therapists or their bona fides who are referred through the Website. We make no and negate any representations or warranties as to the licensure, license status, professional liability insurance, abilities, skills or qualifications of any of the Therapists. Even though We may make a referral, Clients are ultimately and solely responsible for its evaluation, choice of, and all interactions with any Therapist. Clients should always use their best judgment when deciding to engage and to continue to engage with any mental health provider.

# Client Acknowledgements and Agreements
Clients acknowledge and agree (a) We have no obligation to nor do we inquire into the backgrounds, screening, preview, verification, approval or conduct any other due diligence of any Therapist; (b) We simply act as a passive conduit or tool enabling Clients to connect with a Therapist and We do not warrant or represent any particular Therapist is the right fit for a Client; (c) We do not endorse, control nor are We responsible or liable for the conduct, recommendations, advice or activities of any Therapist; (d) it must evaluate and make its own judgment and bear all risks associated with the use of this Website, the Services, the selection of a Therapist, and the relationship with any Therapist; (e) its dealings or interactions and participation with any Therapist, and all other terms, conditions, representations or warranties associated with such dealings, are solely between You and such Therapist; (f) each Therapist unilaterally attests and self-reports whether it has (and the extent of) professional liability insurance, is licensed, and is in good standing with applicable licensing authorities. Client is, therefore, responsible for and should conduct whatever evaluation, background checks, references, investigation or other resources or due diligence that it deems necessary or appropriate before hiring, engaging, or continuing to engage with any Therapist; (g) We are not responsible for the accessibility or unavailability of any Therapist; (h) no Therapist is employed by or affiliated with Us and each is an independent provider who is personally responsible in all respects for the services it provides;  (i) We are not responsible or liable, indirectly or directly, for any damage or loss caused or alleged to be caused by or in connection with any of the foregoing; and (j) it shall be responsible for maintaining the confidentiality of passwords associated with any account it uses to access the Services and the Website.

# Client Indemnification
Each Client shall indemnify, defend, and hold harmless Us and our agents (each an “Indemnified Party") from and against all losses, liabilities, damages, demands, claims, causes of action, judgments, assessments, costs and expenses, including, without limitation, interest, penalties, reasonable attorneys' fees, all expenses incurred in investigating, preparing or defending against any litigation or any type proceeding, commenced or threatened, or any claim whatsoever, and all amounts paid in settlement of any claim or litigation (collectively, "Damages"), asserted against, resulting to, imposed upon, or incurred or suffered by any Indemnified Party, directly or indirectly, as a result of, arising from, or relating directly or indirectly to any (a) violation or breach of this Agreement; (b) use of this Website or the Services; or (c) misrepresentation to Us or any Therapist.

# Therapist representations and warranties
When a Therapist registers on this Website offering psychotherapeutic services, this Agreement applies to all such Therapists. Each Therapist is responsible for the content of its application forms, website, its contact information, all methods of selecting its patients, and the manner of its services. Each Therapist may accept or reject Clients in its sole discretion.

Therapists represent and warrant (a) all information it self-reports and delivers from time to time to Us or any Client will be true, correct, and not misleading which includes, but is not limited to the status of its license and whether he or she is in good standing with all applicable licensing authorities, is subject to disciplinary proceedings by any applicable licensing authority, and whether it maintains (and to what extent) professional liability insurance; (b) not to charge any Client which is referred to it through this Website  more than Fifty Dollars ($50.00) for each of the first four (4) online sessions. Subsequent to the fourth (4th) session, charges for each session is any amount agreed upon with the Client so long as such amount is consistent with the Therapist’s recent historic standard fees; and (c) to be in compliance with all laws, regulations, ethical standards, and insurance contracts and plans applicable to its practice and profession.

# Therapist Indemnification
Each Therapist shall indemnify, defend, and hold harmless Us and our agents (each an “Indemnified Party") from and against all losses, liabilities, damages, demands, claims, causes of action, judgments, assessments, costs and expenses, including, without limitation, interest, penalties, reasonable attorneys' fees, all expenses incurred in investigating, preparing or defending against any litigation or any type proceeding, commenced or threatened, or any claim whatsoever, and all amounts paid in settlement of any claim or litigation (collectively, "Damages"), asserted against, resulting to, imposed upon, or incurred or suffered by any Indemnified Party, directly or indirectly, as a result of, arising from, or relating directly or indirectly to any (a) breach or non-fulfillment of any covenant, representation, agreement or obligation of a Therapist in this Agreement; (b) violation of any applicable law, statute,  regulation or contract by such Therapist including any federal or state privacy law or regulation; (c) your use of, and access to this Website; and (d) negligent act or omission or willful misconduct of a Therapist in performing its mental health services to its patients or to any Client.  

# Disclaimers
CLIENTS AND THERAPISTS AGREE ITS USE OF THE WEBSITE IS AT ITS SOLE RISK. BECAUSE OF THE INHERENT HAZARDS, CORRUPTION, AND UNCERTAINTIES OF ELECTRONIC DISTRIBUTION, THERE MAY BE INTERRUPTIONS, DELAYS, OMISSIONS, INACCURACIES, OR OTHER PROBLEMS WITH THE WEBSITE AND ITS APPLICATIONS. IF CLIENTS OR THERAPISTS RELY ON THE WEBSITE OR ANY MATERIAL AVAILABLE THROUGH IT, IT DOES SO AT ITS OWN RISK. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITE IS DONE AT CLIENT’S AND THERAPIST’S OWN DISCRETION AND RISK AND THEY WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO ITS COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. THE WEBSITE AND ALL SERVICES ARE PROVIDED "AS IS," "WITH ALL FAULTS," AND "AS AVAILABLE." WE DO NOT GUARANTEE THE WEBSITE AND THE SERVICES WILL BE ERROR-FREE, OR CONTINUOUSLY AVAILABLE, OR THAT THE WEBSITE WILL BE FREE OF HARMFUL CODE (AS DEFINED BELOW). WE AND OUR AGENTS WILL NOT BE LIABLE TO CLIENT FOR ANY LOSS OR DAMAGE ARISING OUT OF OR CAUSED IN WHOLE OR IN PART BY HARMFUL CODE. “Harmful Code” means unwanted computer instructions, code, software, circuitry or other technological means whose purpose is to compromise user security, damage, disrupt or interfere with the use of computers, computer systems, data, hosts, or networks. 

SINCE WE DO NOT CONDUCT ANY DUE DILIGENCE, LICENSING VERIFICATIONS OR SCREENINGS OF ANY OF THE THERAPISTS, WE CANNOT AND DO NOT REPRESENT, GUARANTEE OR WARRANT THE SERVICES AND ANY MENTAL HEALTH SERVICES ARE COMPLETE, MERCHANTIBLE, CORRECT, ACCURATE OR ADEQUATE. WE MAKE NO WARRANTIES WHATSOEVER AND DISCLAIM ALL REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRAN­TIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE REGARDING THE SERVICES OR ANY INFORMATION FURNISHED BY US. WE MAKE NO REPRESENTATIONS OR WARRANTIES REGARDING THE RESULTS THE CLIENT WILL ACHIEVE BY USING OR RELYING UPON THE SERVICES OR ITS PROFESSIONAL RELATIONSHIP WITH ANY THERAPIST. CLIENT SHALL BE SOLELY RESPONSIBLE FOR THE MANNER IN WHICH IT USES THE SERVICES INCLUDING ALL INTERACTIONS AND MENTAL HEALTH SERVICES PROVIDED BY ANY THERAPIST. WE AND OUR AGENTS WILL NOT BE LIABLE TO CLIENT FOR ANY LOSS OR DAMAGE ARISING OUT OF OR CAUSED IN WHOLE OR IN PART BY THE SERVICES OR BY ANY INTERACTION OR PROFESSIONAL RELATIONSHIP BETWEEN A THERAPIST AND THE CLIENT.

# Limitations of Liability and Limitations of Actions
EXCEPT TO THE EXTENT OF OUR INTENTIONAL FRAUD, GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR AS OTHERWISE MAY BE PROHIBITED BY LAW, UNDER NO CIRCUMSTANCES SHALL WE (AND OUR AGENTS) BE LIABLE TO ANY CLIENT OR THERAPIST ON ACCOUNT OF SUCH PERSON’S USE OR MISUSE OF OR RELIANCE ON THE WEBSITE OR THE SERVICES. SUCH LIMITATION OF LIABILITY SHALL APPLY TO PREVENT RECOVERY OF INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, AND PUNITIVE DAMAGES WHETHER SUCH CLAIM IS BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), INDEMNITY, OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY. SUCH LIMITATION OF LIABILITY SHALL APPLY WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF OR RELIANCE ON THE WEBSITE, FROM RELIANCE OR DAMAGE CAUSED BY INFORMATION POSTED ON THE WEBSITE, FROM INABILITY TO USE THE WEBSITE, OR FROM THE INTERRUPTION, SUSPENSION, OR TERMINATION OF THE WEBSITE. THIS LIMITATION SHALL ALSO APPLY WITH RESPECT TO (A) DAMAGES INCURRED BY REASON OF ANY OF THE SERVICES OR ANY BREACH OF THIS AGREEMENT BY US; (B) ANY MENTAL HEALTH SERVICES AND ALL CONDUCT, DEALINGS OR INTERACTIONS WITH ANY THERAPIST OR BETWEEN THE THERAPIST AND CLIENT; OR (C) ANYTHING RECEIVED THROUGH OR MADE AVAILABLE ON OR THROUGH THE WEBSITE OR RECEIVED THROUGH ANY LINKS MADE AVAILABLE ON THE WEBSITE. TO THE FULLEST EXTENT PERMITTED BY LAW, THE MAXIMUM AGGREGATE LIABILITY OF US AND OUR AGENTS TO ALL THERAPISTS AND CLIENTS FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, SHALL BE LIMITED TO FIFTY DOLLARS ($50.00). This limitation of liability is cumulative and not per incident. THE EXISTENCE OF ONE OR MORE CLAIMS SHALL NOT ENLARGE THIS LIMITATION. THE REMEDIES IN THIS SECTION ARE CLIENT’S AND THERAPIST’S SOLE AND EXCLUSIVE REMEDIES FOR CLAIMS OR DAMAGES ARISING OUT OF OR RELATING IN ANY WAY TO THIS AGREEMENT, THE USE OF THE WEBSITE, THE SERVICES OR OTHERWISE.  

Except as may be prohibited by applicable law, no lawsuit, claim, Dispute or action  arising out of this Agreement or otherwise for any reason, regardless of form or type of claim, can be commenced by any client or therapist against us (and our liability shall terminate) after one (1) year from when the cause of action accrued. Time is of the essence for this provision.

# Mandatory Arbitration
PLEASE READ THIS SECTION CAREFULLY.  IT AFFECTS RIGHTS THE PARTIES MAY OTHERWISE HAVE. THE PARTIES AGREE, EXCEPT AS OTHERWISE STATED, THERE SHALL BE NO RIGHT TO A JURY OR COURT TRIAL. THE PARTIES AGREE ALL DISPUTES ARE PERSONAL TO THEM AND ALL DISPUTES SHALL ONLY BE RESOLVED BY AN INDIVIDUAL ARBITRATION. THERE CAN BE NO CLASS ARBITRATION OR ARBITRATION WHERE A PERSON BRINGS ACTION OR CLAIM AS A REPRESENTATIVE OF ANY OTHER PERSON OR PERSONS.

Should You have a dispute with respect to any services provided by a Therapist or the fees charged by a Therapist, you must address such dispute with the Therapist directly. Accordingly, and except for all Dispute exclusively between a Therapist and a Client, all claims, disputes or controversies arising out of or relating to any aspect of the relationships between any of the Parties including without limitation this Agreement, the Services, the Website or any mental health services rendered including contract, warranty, statute, regulation, tort, or any other legal or equitable theory, regardless of what remedy is sought (a “Dispute) shall be resolved by binding arbitration in accordance with the terms herein which shall be the sole and exclusive method, means, and procedure to resolve all Disputes arising between the Parties and their respective agents. This agreement to arbitrate and the term Dispute are intended to have the broadest possible construction.

Upon notice (“Notice”) by any Party to any other(s) all unresolved Disputes shall be finally settled by arbitration. The Notice shall be sent by certified mail to the other Party and to JAG (as defined below). The Notice should be delivered by the initiating Party to the other Party(ies) and shall demand arbitration to resolve the Dispute, and shall describe (a) with particularity the nature and factual basis of the Dispute; (b) the legal and/or contractual basis and authority of the Dispute; and (c) the specific relief, and/or proposed solution or remedy sought.

To the maximum extent practicable, the arbitrator and the Parties will take all action required to conclude any arbitration proceeding within one hundred and twenty (120) days of the sending of the Notice. All unresolved Disputes to be arbitrated pursuant hereto shall be determined by binding arbitration before a retired judge, at minimum the district court level, who has at least five (5) years experience in the resolution of disputes, under the auspices of the Judicial Arbiter Group in Denver, CO (“JAG). If JAG is not available the Parties shall agree to another arbitration provider or the Denver County District Court in Denver shall appoint a substitute. The arbitrator shall be chosen by the Parties mutual agreement. If, after ten (10) days from receipt of the Notice, the Parties are unable to agree upon a JAG arbitrator, JAG will appoint the arbitrator. The arbitrator shall apply the substantive law of Colorado, without giving effect to its conflict of law provisions. All face-to-face proceedings shall take place at the offices of JAG in Denver, Colorado.

The arbitration shall be in accordance with this article and the Commercial Arbitration Rules of the American Arbitration Association (“AAA,” but shall not be conducted by the AAA). Notwithstanding those rules, the arbitrator may modify the rules in its discretion to expedite and simplify the hearing. This Agreement governs to the extent it is in conflict with the AAA rules. All discovery activities will be expressly limited to matters directly relevant to the Dispute being arbitrated and the scope and duration of discovery will be determined by the arbitrator based upon the reasonable need for the requested information, the availability of other discovery options and the burdensomeness of the request on the opposing party. The arbitrator may extend deadlines in his or her discretion.

Arbitration is final, non-appealable, and binding. The arbitrator’s decision shall be controlled by this Agreement including without limitation no award shall exceed nor shall the arbitrator have any jurisdiction to make an award to any Party against Us contrary to the “Limitation of Liability” provision in this Agreement and there shall be compliance with the time limitation of bringing a claim as set forth above. The Parties expressly agree the rulings of the arbitrator, including any award, shall be binding on the Parties, non-reviewable and non-appealable and may be entered as a judgment in any court of competent jurisdiction.

The Parties and the arbitrator shall not disclose the Notice, the existence, content or results of the arbitration (all of which between the Parties is deemed confidential) except for disclosures of information by a Party required in the ordinary course of its business, by law, for purposes of enforcement of the arbitration award or to the extent necessary to exercise judicial review rights, if any. Any Party shall have the right in court to prevent any actual or threatened breach of this confidentiality provision by temporary, preliminary or permanent injunctive or declaratory relief.

The Party who sends the Notice shall be responsible for all of the initial deposit to JAG and upon conclusion of the arbitration the Parties shall share equally the fees of JAG.  Each party shall pay its own expenses of the arbitration, including the expense of its own counsel, witnesses, and presentation of evidence at the arbitration. If any Party files a judicial or administrative action asserting a claim or Dispute that is subject to arbitration in accordance with this Agreement and another Party successfully stays such action or compels arbitration, the Party filing that action must pay the other Party’s costs and expenses incurred in seeking such stay or compelling arbitration, including reasonable attorneys’ fees.

# General Provisions
If any term or other provision of this Agreement is held by a court of competent jurisdiction or an arbitrator to be invalid, illegal or incapable of being enforced, all other terms and provisions of this Agreement shall nevertheless remain in full force and effect so long as the economic or legal substance of the transactions contemplated hereby is not affected in any manner materially adverse to any Party.  Upon such determination that any term or other provision is invalid, illegal or incapable of being enforced, the Parties shall negotiate in good faith to modify this Agreement so as to effect the original intent of the Parties as closely as possible in an acceptable manner in order that the transactions contemplated hereby are consummated as originally contemplated to the greatest extent possible.

The Parties intend this Agreement to constitute the complete, exclusive, and fully integrated agreement of the Parties relating to the subject matter hereof. As such, it is the sole repository of their agreement and they are not bound by any other agreements, promises, representations or writings of whatsoever kind or nature made at any time. 

We may terminate any Parties’ privilege to use or access the Website and Services immediately and without notice for any reason whatsoever. Upon such termination, such Party must immediately cease accessing or using the Website and Services and agrees not access or make use of, or attempt to use, the Website and Services. We may exercise this right in our sole discretion, and this right shall be in addition to and not in substitution for any other rights and remedies available to Us. In the event of any termination or expiration of this Agreement, all provisions of this Agreement which by their nature should survive termination shall survive the termination of your access to the Website and Services, including, without limitation, provision regarding, Therapist representations and warranties, disclaimers, indemnity, arbitration, and limitations of liability and action.

We may, in our sole discretion, modify this Agreement at any time effective upon posting the modified Terms of Use on and in connection with the Website and Services, with or without additional notice to you. You are responsible for regularly reviewing information posted on the Website to obtain timely notice of such changes. If you do not agree to the amended terms, you agree to immediately stop using the Website and Services. YOUR CONTINUED USE OF THE WEBSITE AND SERVICES AFTER SUCH POSTING (OR OTHER NOTIFICATION, IF ANY) MEANS YOU ACCEPT AND AGREE TO BE BOUND BY THE MODIFIED TERMS OF USE.

This Agreement and the relationship between any other Party and Us will be governed by the laws of the State of Colorado, notwithstanding the choice of law provisions of the venue where any action is brought, where the violation occurred, where You may be located or any other jurisdiction. With respect to any action involving Us all Parties agree and consent that to the exclusive jurisdiction of the state or federal courts, to the extent, if any, any matter can be brought in court located in Denver County, Colorado and waive any defense of lack of personal jurisdiction or improper venue or forum non-conveniens to a claim brought in such court, except that We may elect, in its sole discretion, to litigate the action in the county or state where any breach by You occurred or where You can be found.
`;

export default terms;
